language: java
deploy:
 skip_cleanup: true
 provider: heroku
 app: peliculas-grupo4
  secure: x33jpbYT9UrP3KJ5nJMdQyXi7z7wIq0SCcYOmlnrWpUxcbJBcf9giXkgpvB1QZc8gQNJp6tpLYgCwAymEx9ZYxPR/QCG2qfHz2pY7aw16bHMDW83ca/smafBSJobbbaz0TqTFPXm95TBhql71KH5OwOLHGAtwEjZfiZQLdFZowGDWIIkEodLTfJhDDtNk7EpZpQywvext7hOitkq1VimEyFTYjGmvFTKDsIiJws9Y21t91sFHgkiZEz7rouaDdv4qHiZCpAoIJrGZzRezsmAUu//y1yJbzIo5R3zs5uWKPKL6zUPi8jVfP+1fH1CVGBaZErxRDBgNRkbUALl7jA4N/H35FyZmpIBLeOXB2aTKgFT7WdQeMWY05Zi7JtXMFvLlMnt/QPobU5DvqfnW1VK3iwqIGKMBAfOouhHtd6eDsU3Nwu4ICyyluR5tOoMnwCD36Z/7dogBf51BHDZlMHat4xdiQq+5INUrsi0gEy9iN5yzBztslXIiryjfdwSpdH7NEgmM5UDFf0CJZQKzTcS9VGbC92AoNH6gGzgxTJkGPfwaKqLXhRpgaC3bv6bbbMQLgOGhMfQ5Rqq2HFVa5iX3jI925ijg4B5IWo1aegGcxQfGQ6GfN1ay53IhWfPv9C/tF5UkIMeHOPGWKTkkukGjQBm58OuGLskkbaivAMX5+s=
